# Generated by Django 2.2.16 on 2020-11-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
